#!/usr/bin/env python3

"""
Entry point for GTK application.
"""

from gui import window
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

def main():
    win = window.MainWindow()
    win.connect("destroy", Gtk.main_quit)
    win.show_all()
    Gtk.main()

if __name__ == "__main__":
    main()
